# Generated by Django 3.2 on 2021-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
